[project]
name = "mcp-server"
version = "0.1.0"
description = "MCP Server for weather data"
requires-python = ">=3.10"
dependencies = [
    "mcp[cli]",
    "httpx",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["app"] 
